"use client";
import { OfficialSiteLink } from "./official-site-link";
import { useState } from "react";
import { ArrowRight, Check, Compass, PenLine, ShieldCheck, Store } from "lucide-react";
import type { Page, Role } from "@/lib/game-types";
import { ClientWordmark } from "./client-wordmark";
export function ReferenceEntry({ onEnter, ready, error, onRetry, theme, showWorkspaceEntries = true }: { onEnter:(page:Page)=>void;ready:boolean;error:string;onRetry:()=>void;theme:"light"|"dark";showWorkspaceEntries?:boolean }) {
  const [role,setRole]=useState<Role>("hunter");
  return <main className="auth-shell client-shell reference-client" data-client-theme={theme}><div className="auth-orb auth-orb-one"/><div className="auth-orb auth-orb-two"/><section className="auth-panel"><ClientWordmark onHome={() => onEnter("entry")} className="auth-brand-intro quest-auth-wordmark"/><div className="auth-content-intro"><div className="official-site-return-row"><OfficialSiteLink /></div><h1>把世界变成一场寻宝游戏</h1><p className="auth-lead">在商场角落发现惊喜，或亲手为他人埋下一份宝藏。</p><div className="role-picker"><p className="field-label">选择你的角色</p><div className="role-options">{([{role:"hunter",title:"寻宝者",desc:"寻找宝藏，收集卡片",icon:Compass},{role:"explorer",title:"探索者",desc:"分享线索，创造惊喜",icon:PenLine}] as const).map(({role:next,title,desc,icon:Icon})=><button key={next} className={`role-card${role===next?" selected":""}`} onClick={()=>setRole(next)} type="button" aria-pressed={role===next}><span className="role-icon"><Icon size={24}/></span><span><b>{title}</b><small>{desc}</small></span><i><Check size={14}/></i></button>)}</div></div><button className="primary-button" aria-label={role==="hunter"?"开始寻宝":"去创作"} onClick={()=>onEnter(role==="hunter"?"map":"placements")} type="button">开启旅程<ArrowRight size={18}/></button><p className="terms">同一个账号，既能寻找，也能创造。</p>{showWorkspaceEntries && <div className="reference-workspace-entry"><button type="button" onClick={()=>onEnter("merchant")}><Store size={17}/>商家端</button><button type="button" onClick={()=>onEnter("staff")}><ShieldCheck size={17}/>运营端</button></div>}{!ready&&!error&&<p role="status" className="terms">正在连接商场…</p>}{error&&<div className="error-banner" role="alert"><p>{error}</p><button className="text-button" onClick={onRetry}>重新连接</button></div>}</div></section></main>;
}
