import { ArrowRight, MapPin, Ticket, ClipboardCheck, Users } from "lucide-react";
import { Link } from "react-router-dom";
import PageHeader from "@/components/layout/PageHeader";
import { promotionStrategies, cooperationModels, scenarios } from "@/data/product";
import { PRODUCT_URL } from "@/data/contacts";
const preparations=[
 {icon:MapPin,title:"场地与定位",text:"选择安全可达的点位，配置门店范围，并用实际手机检查现场定位。"},
 {icon:Ticket,title:"金币与奖励",text:"将金币设备绑定到任务，确认奖励条件、有效期、库存和领取步骤。"},
 {icon:ClipboardCheck,title:"现场操作",text:"门店先走通领取申请、收回金币、确认奖励和个人券核销。"},
 {icon:Users,title:"内容与参与",text:"准备线索并审核，邀请少量玩家试用，记录实际问题后迭代。"}
];
export default function ProductDetail(){
 return <><PageHeader dark eyebrow="功能与落地" title="从一次小探索，" highlight="开始试点。" description="先把现场流程走通，再用真实记录和反馈判断活动效果。" />
 <section className="bg-cream-100 py-16 lg:py-24"><div className="container"><div className="reveal mb-10 max-w-2xl"><p className="text-sm tracking-widest text-forest-600">落地准备</p><h2 className="mt-4 font-display text-3xl font-bold text-navy-950 sm:text-5xl">让每个点位，<br/>都准备好被发现。</h2></div><div className="grid gap-6 md:grid-cols-2">{preparations.map((item,index)=>{const Icon=item.icon;return <article key={item.title} className={`reveal reveal-delay-${index%2+1} rounded-3xl border border-navy-900/5 bg-white p-8`}><Icon className="h-7 w-7 text-forest-600"/><h3 className="mt-5 font-display text-2xl font-bold text-navy-950">{item.title}</h3><p className="mt-4 leading-relaxed text-navy-800/60">{item.text}</p></article>})}</div><p className="reveal mt-7 max-w-3xl text-sm leading-relaxed text-navy-800/60">现场使用需要手机联网并授权定位；定位和相机扫码需在 HTTPS 环境验收。定位表现受设备与现场环境影响，正式试点前应逐一测试。</p></div></section>
 <section className="bg-navy-950 py-16 text-cream-100 lg:py-24"><div className="container"><div className="reveal mb-10 max-w-2xl"><p className="text-sm tracking-widest text-forest-300">试点流程</p><h2 className="mt-4 font-display text-3xl font-bold sm:text-5xl">先做小，<br/>再做好。</h2></div><ol className="grid gap-6 md:grid-cols-2 lg:grid-cols-4">{promotionStrategies.map((stage,index)=><li key={stage.phase} className={`reveal reveal-delay-${index+1} rounded-3xl border border-forest-300/20 bg-navy-900/60 p-7`}><span className="font-mono text-3xl text-forest-300">{stage.phase}</span><h3 className="mt-6 font-display text-xl font-bold">{stage.title}</h3><p className="mt-4 text-sm leading-relaxed text-cream-100/60">{stage.desc}</p></li>)}</ol></div></section>
 <section id="scenarios" className="bg-white py-16 lg:py-24"><div className="container"><div className="reveal mb-10"><p className="text-sm tracking-widest text-forest-600">适用场景</p><h2 className="mt-4 font-display text-3xl font-bold text-navy-950 sm:text-5xl">给熟悉的地方，<br/>一个新的探索理由。</h2></div><div className="grid gap-6 lg:grid-cols-3">{scenarios.map((scenario,index)=><article key={scenario.title} className={`reveal reveal-delay-${index+1} rounded-3xl bg-cream-100 p-8`}><h3 className="font-display text-2xl font-bold text-navy-950">{scenario.title}</h3><p className="mt-4 leading-relaxed text-navy-800/60">{scenario.desc}</p></article>)}</div></div></section>
 <section className="bg-cream-100 py-16 lg:py-24"><div className="container"><div className="reveal mb-10 max-w-2xl"><p className="text-sm tracking-widest text-forest-600">各自负责，协作完成</p><h2 className="mt-4 font-display text-3xl font-bold text-navy-950 sm:text-5xl">探索背后，<br/>有人把细节准备好。</h2></div><div className="grid gap-6 lg:grid-cols-3">{cooperationModels.map((role,index)=><article key={role.role} className={`reveal reveal-delay-${index+1} rounded-3xl border border-navy-900/5 bg-white p-8`}><h3 className="font-display text-2xl font-bold text-navy-950">{role.role}</h3><p className="mt-5 leading-relaxed text-navy-800/70">{role.responsibility}</p><p className="mt-4 text-sm leading-relaxed text-forest-700">{role.benefit}</p></article>)}</div><div className="reveal mt-10 rounded-3xl border border-navy-900/10 p-8"><h3 className="font-display text-xl font-bold text-navy-950">效果，用实际体验来回答。</h3><p className="mt-4 max-w-3xl leading-relaxed text-navy-800/60">关注参与、领奖、优惠券使用和现场反馈。客流增长、停留时长、会员互通和商业服务需要后续试点或接入验证，当前不预设提升比例。</p><div className="mt-7 flex flex-wrap items-center gap-5"><a href={PRODUCT_URL} className="product-cta inline-flex items-center gap-2 rounded-full bg-navy-950 px-6 py-3 font-semibold text-cream-100">体验产品 <ArrowRight className="h-4 w-4"/></a><Link to="/team#contact" className="inline-flex items-center gap-2 text-sm font-semibold text-forest-700 hover:underline">联系团队成员 <ArrowRight className="h-4 w-4"/></Link></div></div></div></section></>;
}
