import { useState } from "react";
import { Link } from "react-router-dom";
import { ArrowRight, MapPin, Radio, Users, Ticket, ShieldCheck, BarChart3, Compass, Store, PenLine } from "lucide-react";
import PageHeader from "@/components/layout/PageHeader";
import { coreFeatureDetails } from "@/data/product";
import { PRODUCT_URL } from "@/data/contacts";
const icons = [MapPin, Radio, Users, Ticket, ShieldCheck, BarChart3];
const experiences = [
 {name:"寻宝与创作",icon:PenLine,headline:"每个人都可以留下自己的发现。",items:["在地图选择宝藏，查看门店与分级线索。","找到金币后碰 NFC，通过到店校验并保存领取申请。","查看卡包与积分；也可以创作线索，提交审核。"]},
 {name:"门店管理",icon:Store,headline:"从金币领取，到个人券核销。",items:["设置门店范围，维护优惠券库存与金币设备绑定。","识别金币设备，核对玩家并接收实物后确认奖励。","日后消费时扫描个人券二维码核销，查看本店记录。"]},
 {name:"运营审核",icon:ShieldCheck,headline:"让每一次探索有内容，也有规则。",items:["审核账号、门店申请、探索内容与活动。","维护发布状态、游戏设置及相关记录。","根据实际反馈安排内容与流程改进。"]}
] as const;
export default function Product() {
 const [selected,setSelected]=useState(0);
 const experience=experiences[selected];
 const Icon=experience.icon;
 return <><PageHeader dark eyebrow="产品介绍" title="去探索，" highlight="去发现。" description="逛道宝用地图、线索和金币，把一次路过变成一场真实的线下探索。" />
 <section className="bg-cream-100 py-16 lg:py-24"><div className="container"><div className="reveal grid items-start gap-10 lg:grid-cols-[1fr_1.2fr]"><div><p className="text-sm tracking-widest text-forest-600">三端，一场完整体验</p><h2 className="mt-4 font-display text-3xl font-bold leading-tight text-navy-950 sm:text-5xl">玩家的发现，<br />门店的回应。</h2><p className="mt-5 max-w-lg leading-relaxed text-navy-800/60">寻宝者与探索者属于同一客户端。门店管理和运营审核由各自账号进入工作台。</p><a href={PRODUCT_URL} className="product-cta mt-7 inline-flex items-center gap-2 rounded-full bg-navy-950 px-6 py-3 font-semibold text-cream-100">体验产品 <ArrowRight className="h-4 w-4" /></a></div><div className="rounded-3xl border border-navy-900/5 bg-white p-6 sm:p-8"><div className="flex flex-wrap gap-2" role="group" aria-label="选择要了解的功能">{experiences.map((item,index)=><button key={item.name} type="button" aria-pressed={selected===index} onClick={()=>setSelected(index)} className={`rounded-full px-4 py-2 text-sm font-medium transition-colors ${selected===index?"bg-navy-950 text-cream-100":"bg-cream-100 text-navy-800 hover:bg-forest-100"}`}>{item.name}</button>)}</div><div key={selected} className="role-panel mt-8" aria-live="polite"><Icon className="h-8 w-8 text-forest-600" /><h3 className="mt-5 font-display text-2xl font-bold text-navy-950">{experience.headline}</h3><ul className="mt-6 space-y-4">{experience.items.map((item,index)=><li key={item} className="flex gap-3 text-sm leading-relaxed text-navy-800/70"><span className="font-mono text-forest-600">0{index+1}</span><span>{item}</span></li>)}</ul></div></div></div></div></section>
 <section className="bg-white py-16 lg:py-24"><div className="container"><div className="reveal mb-10 max-w-2xl"><p className="text-sm tracking-widest text-forest-600">核心功能</p><h2 className="mt-4 font-display text-3xl font-bold text-navy-950 sm:text-5xl">每一步，都有下一步。</h2></div><div className="grid gap-6 md:grid-cols-2 lg:grid-cols-3">{coreFeatureDetails.map((feature,index)=>{const FeatureIcon=icons[index] || MapPin;return <article key={feature.title} className={`reveal reveal-delay-${index%3+1} rounded-3xl border border-navy-900/5 bg-cream-100 p-7`}><FeatureIcon className="h-7 w-7 text-forest-600"/><h3 className="mt-6 font-display text-xl font-bold text-navy-950">{feature.title}</h3><p className="mt-4 leading-relaxed text-navy-800/70">{feature.description}</p><p className="mt-4 text-sm leading-relaxed text-navy-800/60">{feature.implement}</p></article>})}</div></div></section>
 <section className="bg-cream-100 py-16 lg:py-24"><div className="container"><div className="reveal grid items-center gap-8 rounded-[2rem] bg-navy-950 p-8 text-cream-100 sm:p-12 lg:grid-cols-2"><Compass className="hidden h-24 w-24 text-forest-300 lg:block"/><div><h2 className="font-display text-3xl font-bold">从第一条线索开始。</h2><p className="mt-5 leading-relaxed text-cream-100/60">先体验玩法，再了解门店如何准备、活动怎样开展。</p><div className="mt-7 flex flex-wrap gap-4"><a href={PRODUCT_URL} className="product-cta inline-flex items-center gap-2 rounded-full bg-forest-300 px-6 py-3 font-semibold text-navy-950">体验产品 <ArrowRight className="h-4 w-4"/></a><Link to="/product/detail" className="inline-flex items-center gap-2 px-2 py-3 text-forest-300 hover:underline">了解落地流程 <ArrowRight className="h-4 w-4"/></Link></div></div></div></div></section></>;
}
